### ISSUE TITLE
TypeError: get_figure() missing 1 required positional argument: 'theme'

### ISSUE THREAD

**Issue by dalmei33** [vappiah/manhattan-plots#1]
Hi

Thank you so much for your tutorial for making manhattan-plots using FST values. 
I was able to successfully use your scripts with my "sorted_filtered_variants.vcf.gz" file, meaning that I got my "snps.filtered.vcf.gz" file. 

However, when trying to plot the FST values I get this error:

((fst-env) [dmalmei@node1921 manhattan-plots]$ python3 plot_fst.py 22_chromosomes_neg_vs_pos_ventral.newheader.fst.weir.fst
Traceback (most recent call last):
  File "plot_fst.py", line 13, in <module>
    mhat(selected,chr='CHROM',fst='WEIR_AND_COCKERHAM_FST',show=False,color=('black','red'))
  File "/scratch1/dmalmei/9xx_Remove_filtered_variants/b_FST_genome_scan/manhattan-plots/manhattan.py", line 85, in mhat
    general.get_figure(show, r, figtype, figname)
TypeError: get_figure() missing 1 required positional argument: 'theme'
(fst-env) [dmalmei@node1921 manhattan-plots]$ 

Can you please help me to solve it? 

Thanks!

**Comment by vappiah** [comment]
Hi @dalmei33  the scripts were written to analyze variants for _P.__falciparum_. If you are using it for human genomes then you have to do some modification.

I am planning to write a more generic script. But in the meantime, you may have to modify to suit your needs.
